input_data : '/Volumes/uc-dev/data/samples/hotel_reservations.csv'

parameters:
  learning_rate: 0.01
  n_estimators: 1000
  max_depth: 6

test_size: 0.2
random_state: 42

num_features:
  - LotFrontage 
  - LotArea
  - OverallQual
  - OverallCond
  - YearBuilt
  - YearRemodAdd
  - MasVnrArea
  - TotalBsmtSF
  - GrLivArea
  - GarageCars

cat_features:
  - MSZoning
  - Street
  - Alley
  - LotShape
  - LandContour
  - Neighborhood
  - Condition1
  - BldgType
  - HouseStyle
  - RoofStyle
  - Exterior1st
  - Exterior2nd
  - MasVnrType
  - Foundation
  - Heating
  - CentralAir
  - SaleType
  - SaleCondition

target: SalePrice