# Input Data
input_data : '/Volumes/uc_dev/hotel_reservation/samples/hotel_reservations.csv'

# Mlflow Config
experiment_name: /Shared/hotel-reservations

# Data Preprocessing Config
test_size: 0.2
random_state: 42

# Model Config
parameters:
  random_state: 42
  n_estimators: 300
  max_depth: 6
  learning_rate: 0.01

id_columns: 
  - Booking_ID

num_features:
  - no_of_adults
  - no_of_children
  - no_of_weekend_nights
  - no_of_week_nights
  - required_car_parking_space
  - lead_time
  - arrival_year
  - arrival_month
  - arrival_date
  - repeated_guest
  - no_of_previous_cancellations
  - no_of_previous_bookings_not_canceled
  - avg_price_per_room
  - no_of_special_requests

cat_features:
  - type_of_meal_plan
  - room_type_reserved
  - market_segment_type

target: booking_status

# Catalog
prod:
  catalog_name: uc_prod
  schema_name: hotel_reservation
  pipeline_id: 2e48de81-2d9a-4c9d-b18f-10064d7713df 
qa:
  catalog_name: uc_qa
  schema_name: hotel_reservation
  pipeline_id: 2e48de81-2d9a-4c9d-b18f-10064d7713df 
dev:
  catalog_name: uc_dev
  schema_name: hotel_reservation
  pipeline_id: 2e48de81-2d9a-4c9d-b18f-10064d7713df 

# Endpoint
endpoint_name: hotel-reservation-model-serving-fe
